//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.Application.Identity.Resources.Accounts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AccountsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmployeeManagement.Application.Identity.Resources.Accounts.AccountsRes", typeof(AccountsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Acount Already Blocked.
        /// </summary>
        internal static string AccountBlock {
            get {
                return ResourceManager.GetString("AccountBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve tried so many times to login to your account, and for security purposes, your account has been suspended. Please, try again after 5 minutes..
        /// </summary>
        internal static string AccountIsLockedOutError {
            get {
                return ResourceManager.GetString("AccountIsLockedOutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found blocked account.
        /// </summary>
        internal static string AccountNotBlock {
            get {
                return ResourceManager.GetString("AccountNotBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already conffirmed.
        /// </summary>
        internal static string AlreadyConfirmed {
            get {
                return ResourceManager.GetString("AlreadyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t change Email for this account.
        /// </summary>
        internal static string CannotChangeExisting {
            get {
                return ResourceManager.GetString("CannotChangeExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using Claro Eg &quot;{0}&quot;.
        /// </summary>
        internal static string ConfirmMessage {
            get {
                return ResourceManager.GetString("ConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been banned.
        /// </summary>
        internal static string DeactivatedError {
            get {
                return ResourceManager.GetString("DeactivatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been deleted.
        /// </summary>
        internal static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account with this email already exists.
        /// </summary>
        internal static string ExistingEmail {
            get {
                return ResourceManager.GetString("ExistingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account provider isn&apos;t registered with any user.
        /// </summary>
        internal static string ExternalUserNotFound {
            get {
                return ResourceManager.GetString("ExternalUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FailedToLoginError.
        /// </summary>
        internal static string FailedToLoginError {
            get {
                return ResourceManager.GetString("FailedToLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This country&apos;s phone numbers aren&apos;t supported.
        /// </summary>
        internal static string InvalidCodeCountry {
            get {
                return ResourceManager.GetString("InvalidCodeCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Connector is not valid.
        /// </summary>
        internal static string InValidConnector {
            get {
                return ResourceManager.GetString("InValidConnector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not correct .
        /// </summary>
        internal static string InValidPassword {
            get {
                return ResourceManager.GetString("InValidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is Invalid Phone Number.
        /// </summary>
        internal static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This token is invalid or expired.
        /// </summary>
        internal static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new email matches the old one.
        /// </summary>
        internal static string NewEmailMatchesOldOne {
            get {
                return ResourceManager.GetString("NewEmailMatchesOldOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be at least &quot;{0}&quot;and at max &quot;{1}&quot; characters long.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account is not found.
        /// </summary>
        internal static string NotFoundAccount {
            get {
                return ResourceManager.GetString("NotFoundAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be at least &quot;{0}&quot;and at max &quot;{1}&quot; characters long.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account with this number already exists.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        internal static string RequiredEmail {
            get {
                return ResourceManager.GetString("RequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Role isn&apos;t exist.
        /// </summary>
        internal static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem with this account , please try another way .
        /// </summary>
        internal static string TryAnotherWay {
            get {
                return ResourceManager.GetString("TryAnotherWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account can&apos;t be banned.
        /// </summary>
        internal static string Unbanable {
            get {
                return ResourceManager.GetString("Unbanable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account can&apos;t be deleted.
        /// </summary>
        internal static string Undeletable {
            get {
                return ResourceManager.GetString("Undeletable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no user registered with this email.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no user registered with this phone.
        /// </summary>
        internal static string UserPhoneNotFound {
            get {
                return ResourceManager.GetString("UserPhoneNotFound", resourceCulture);
            }
        }
    }
}
