namespace EmployeeManagement.Application.Common.Enums
{
    public enum PhoneNumberCode
    {
        Afghanistan                 = 93_09,
        Albania                     = 355_09, // Uncertain
        Algeria                     = 213_09,
        AmericanSamoa               = 684_10, // Uncertain
        Andorra                     = 376_09, // Uncertain
        Angola                      = 244_09, // Uncertain
        Anguilla                    = 264_10, // Uncertain
        AntiguaAndBarbuda           = 268_10, // Uncertain
        Argentina                   = 54_09,  // Uncertain
        Armenia                     = 374_06,
        Aruba                       = 297_07,
        Ascension                   = 247_09, // Uncertain
        Australia                   = 61_09,
        Austria                     = 43_10,
        Azerbaijan                  = 994_09,
        Bahamas                     = 242_10, // Uncertain
        Bahrain                     = 973_08,
        Bangladesh                  = 880_10,
        Barbados                    = 246_10, // Uncertain
        Belarus                     = 375_09,
        Belgium                     = 32_09,
        Belize                      = 501_07,
        Benin                       = 229_06, // Uncertain
        Bermuda                     = 441_10,
        Bhutan                      = 975_09, // Uncertain
        Bolivia                     = 591_09, // Uncertain
        Bonaire                     = 599_09, // Uncertain,
        SintEustatiusAndSaba        = 599_09, // Uncertain
        BosniaAndHerzegovina        = 387_08, // Uncertain
        Botswana                    = 267_09, // Uncertain
        Brazil                      = 55_11,
        BritishIndianOceanTerritory = 246_07, // Uncertain
        BritishVirginIslands        = 284_10, // Uncertain
        Brunei                      = 673_09, // Uncertain
        Bulgaria                    = 359_09,
        BurkinaFaso                 = 226_08,
        Burundi                     = 257_09, //Uncertain
        Cambodia                    = 855_09,
        Cameroon                    = 237_09,
        Canada                      = 1_10,
        CentralAfricanRepublic      = 236_09, //Uncertain
        Chad                        = 235_08,
        Chile                       = 56_09,
        China                       = 86_11,
        Colombia                    = 57_10,
        Comoros                     = 269_09, //Uncertain
        CookIslands                 = 682_05,
        CostaRica                   = 506_08,
        Croatia                     = 385_09,
        Cuba                        = 53_09,  //Uncertain
        Curaçao                     = 599_09, //Uncertain
        Cyprus                      = 357_08,
        CzechRepublic               = 420_09,
        Denmark                     = 45_08,
        Djibouti                    = 253_09, //Uncertain
        Ecuador                     = 593_09,
        Egypt                       = 20_10,
        England                     = 44_10,
        Eritrea                     = 291_09, //Uncertain
        Estonia                     = 372_09, //Uncertain
        Eswatini                    = 268_08,
        Ethiopia                    = 251_09, //Uncertain
        FalklandIslands             = 500_05,
        FaroeIslands                = 298_05,
        Fiji                        = 679_09, //Uncertain
        Finland                     = 358_10,
        France                      = 33_09,
        Gabon                       = 241_07,
        Gambia                      = 220_09, //Uncertain
        Georgia                     = 995_09,
        Germany                     = 49_10,
        Ghana                       = 233_09,
        Gibraltar                   = 350_09, //Uncertain
        Greece                      = 30_10,
        Greenland                   = 299_06,
        Grenada                     = 473_10,
        Guadeloupe                  = 590_09,
        Guam                        = 671_10,
        Guatemala                   = 502_08,
        Guyana                      = 592_09, //Uncertain
        Haiti                       = 509_09, //Uncertain
        Honduras                    = 504_08,
        HongKong                    = 852_08,
        Hungary                     = 36_09,
        Iceland                     = 354_09, //Uncertain
        India                       = 91_10,
        Indonesia                   = 62_09,
        Iraq                        = 964_10,
        Iran                        = 98_09, //Uncertain
        Ireland                     = 353_09,
        Israel                      = 972_09,
        Italy                       = 39_44452,
        Jamaica                     = 658_10,
        Japan                       = 81_10,
        Jordan                      = 962_09,
        Kazakhstan                  = 7_10,
        Kenya                       = 254_10,
        Kiribati                    = 686_08,
        Kosovo                      = 383_08,
        Kuwait                      = 965_08,
        Kyrgyzstan                  = 996_09, //Uncertain
        Laos                        = 856_09, //Uncertain
        Latvia                      = 371_08,
        Lebanon                     = 961_07,
        Lesotho                     = 266_09, //Uncertain
        Liberia                     = 231_07,
        Libya                       = 218_10,
        Liechtenstein               = 423_09, //Uncertain
        Lithuania                   = 370_08,
        Luxembourg                  = 352_09,
        Macau                       = 853_09, //Uncertain
        Madagascar                  = 261_09, //Uncertain
        Malawi                      = 265_09, //Uncertain
        Malaysia                    = 60_07,
        Maldives                    = 960_07,
        Mali                        = 223_08,
        Malta                       = 356_08,
        MarshallIslands             = 692_07,
        Martinique                  = 596_09,
        Mauritania                  = 222_09, //Uncertain
        Mauritius                   = 230_08,
        Mayotte                     = 262_09, //Uncertain
        Mexico                      = 52_10,
        Moldova                     = 373_08,
        Monaco                      = 377_09, //Uncertain
        Mongolia                    = 976_08,
        Montenegro                  = 382_08,
        Montserrat                  = 664_10,
        Morocco                     = 212_09, //Uncertain
        Mozambique                  = 258_12,
        Myanmar                     = 95_08,
        Namibia                     = 264_09, //Uncertain
        Nauru                       = 674_09, //Uncertain
        Netherlands                 = 31_09,
        Nepal                       = 977_10,
        NewCaledonia                = 687_06,
        NewZealand                  = 64_08,
        Nicaragua                   = 505_08,
        Niger                       = 227_08,
        Nigeria                     = 234_08,
        Niue                        = 683_04,
        Norway                      = 47_08,
        Oman                        = 968_08,
        Pakistan                    = 92_10,
        Palau                       = 680_07,
        Palestine                   = 970_09,
        Panama                      = 507_08,
        Paraguay                    = 595_09,
        Peru                        = 51_09,
        Philippines                 = 63_10,
        Poland                      = 48_09,
        Portugal                    = 351_09,
        Qatar                       = 974_08,
        Reunion                     = 262_09,
        Romania                     = 40_10,
        Russia                      = 7_10,
        Rwanda                      = 250_09, //Uncertain
        Samoa                       = 685_05,
        SaoTomeAndPrincipe          = 239_09, //Uncertain
        SaudiArabia                 = 966_09,
        Senegal                     = 221_09, //Uncertain
        Serbia                      = 381_08,
        Seychelles                  = 248_09, //Uncertain
        SierraLeone                 = 232_09, //Uncertain
        SintMaarten                 = 721_10,
        Singapore                   = 65_08,
        Slovakia                    = 421_09,
        Slovenia                    = 386_09, //Uncertain
        SolomonIslands              = 677_07,
        Somalia                     = 252_07,
        SouthAfrica                 = 27_09,
        SouthKorea                  = 82_09,
        SouthSudan                  = 211_09, //Uncertain
        Spain                       = 34_09,
        SriLanka                    = 94_07,
        Sudan                       = 249_09, //Uncertain
        Suriname                    = 597_09, //Uncertain
        Sweden                      = 46_07,  //Uncertain
        Switzerland                 = 41_09,
        Syria                       = 963_09,
        Taiwan                      = 886_09,
        Tajikistan                  = 992_09, //Uncertain
        Tanzania                    = 255_09, //Uncertain
        Thailand                    = 66_09,
        TimorLeste                  = 670_09, //Uncertain
        Togo                        = 228_08,
        Tokelau                     = 690_09, //Uncertain
        Tonga                       = 676_09, //Uncertain
        TrinidadAndTobago           = 868_10,
        Tunisia                     = 216_08,
        Turkey                      = 90_11,
        Turkmenistan                = 993_09, //Uncertain
        TurksAndaicosIslands        = 649_10,
        Tuvalu                      = 688_09, //Uncertain
        Uganda                      = 256_09, //Uncertain
        Ukraine                     = 380_09,
        UnitedArabEmirates          = 971_09,
        UnitedKingdom               = 44_10,
        UnitedStates                = 1_10,
        Uruguay                     = 598_09, //Uncertain
        Uzbekistan                  = 998_09, //Uncertain
        Vanuatu                     = 678_09, //Uncertain
        Venezuela                   = 58_07,
        Vietnam                     = 84_09,
        VirginIslands               = 340_10,
        WallisAndFutuna             = 681_09, //Uncertain
        WestBank                    = 970_09, //Uncertain
        Yemen                       = 967_09,
        Zambia                      = 260_09, //Uncertain
        Zimbabwe                    = 263_09
    }
}
